# general
title: PicoCTF 2021 Writeups
description: Writeups for the 2021 PicoCTF challenges I have completed
author: Bsnookie9
# theme
theme: jekyll-theme-hacker
# Github flavored markdown
markdown: GFM
